# Stage 1: Build the Vite app
FROM node:16 AS build

# Install git
RUN apt-get update && apt-get install -y git

# Set the working directory
WORKDIR /app

# Clone the repository
RUN git clone https://github.com/hung27422/clinic_interface.git

# Install dependencies
RUN cd ./clinic_interface && npm install

ENV VITE_API_URL=http://localhost:8080/api

# Build the Vite app
RUN cd ./clinic_interface && npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine

# Copy built files from the build stage
COPY --from=build /app/clinic_interface/dist /usr/share/nginx/html
# Copy custom Nginx configuration if needed
# COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
