version: "3.4"

services:
    clinical-get-back:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Clinical123
        ports:
            - "8080:8080"
            - "8081:8081"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - ./.container/logs:/logs
        depends_on:
            - postgres
        command: >
            /bin/sh -c "dotnet Clinical-get-back.dll"
    front-end:
        build:
            dockerfile: Dockerfile_Frontend
            context: .
        ports:
            - "80:80"
        depends_on:
            - clinical-get-back

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: ClinicalDB
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
